
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var r={},t;for(t in e)e.hasOwnProperty(t)&&(r[t]=e[t]);var aa="./this.program",x="",ba;x=self.location.href;x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"";ba=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var ca=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(e[t]=r[t]);
r=null;e.thisProgram&&(aa=e.thisProgram);var A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var C,da=new WebAssembly.Table({initial:604,maximum:604,element:"anyfunc"}),ea=!1,fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&fa)return fa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|l:(f&7)<<18|h<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function ia(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0}}
function ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function la(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ma[c];)++c;c<<=1;if(32<c-a&&ka)return ka.decode(D.subarray(a,c));c=0;for(d="";;){var f=E[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}
function na(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d}function oa(a){return 2*a.length}function pa(a,b){for(var c=0,d="";!(c>=b/4);){var f=F[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function qa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}F[b>>2]=h;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,H,D,E,ma,F,I,sa,ta;
function ua(a){G=a;e.HEAP8=H=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=ma=new Uint16Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=sa=new Float32Array(a);e.HEAPF64=ta=new Float64Array(a)}var va=e.INITIAL_MEMORY||16777216;e.wasmMemory?C=e.wasmMemory:C=new WebAssembly.Memory({initial:va/65536,maximum:32768});C&&(G=C.buffer);va=G.byteLength;ua(G);F[7160]=5271680;
function wa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Na;"number"===typeof c?void 0===b.Fa?e.dynCall_v(c):e.dynCall_vi(c,b.Fa):c(void 0===b.Fa?null:b.Fa)}}}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=e.preRun.shift();xa.unshift(a)}var J=0,Ca=null,Da=null;e.preloadedImages={};e.preloadedAudios={};function B(a){if(e.onAbort)e.onAbort(a);ca(a);y(a);ea=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ea(){var a=K;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var K="puzzle.wasm";if(!Ea()){var Fa=K;K=e.locateFile?e.locateFile(Fa,x):x+Fa}function Ga(){try{if(A)return new Uint8Array(A);if(ba)return ba(K);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}
function Ha(){return A||"function"!==typeof fetch?new Promise(function(a){a(Ga())}):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ga()})}ya.push({Na:function(){Ia()}});function Ja(){return 0<Ja.Ja}var Ka={},La=[null,[],[]],Ma={};function Na(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Oa=void 0;
function L(a){for(var b="";D[a];)b+=Oa[D[a++]];return b}var M={},N={},Pa={};function Qa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ra(a,b){a=Qa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Sa(a){var b=Error,c=Ra(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var O=void 0;function P(a){throw new O(a);}var Ta=void 0;function Ua(a){throw new Ta(a);}
function Q(a,b,c){function d(k){k=c(k);k.length!==a.length&&Ua("Mismatched type converter count");for(var p=0;p<a.length;++p)R(a[p],k[p])}a.forEach(function(k){Pa[k]=b});var f=Array(b.length),h=[],l=0;b.forEach(function(k,p){N.hasOwnProperty(k)?f[p]=N[k]:(h.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(function(){f[p]=N[k];++l;l===h.length&&d(f)}))});0===h.length&&d(f)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(N.hasOwnProperty(a)){if(c.Qa)return;P("Cannot register type '"+d+"' twice")}N[a]=b;delete Pa[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(f){f()}))}function Va(a){return{count:a.count,ta:a.ta,wa:a.wa,ja:a.ja,ka:a.ka,na:a.na,oa:a.oa}}
function Wa(a){P(a.ha.ka.ia.name+" instance already deleted")}var Xa=!1;function Ya(){}function Za(a){--a.count.value;0===a.count.value&&(a.na?a.oa.sa(a.na):a.ka.ia.sa(a.ja))}
function $a(a){if("undefined"===typeof FinalizationGroup)return $a=function(b){return b},a;Xa=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.ja?Za(c):console.warn("object already deleted: "+c.ja)});$a=function(b){Xa.register(b,b.ha,b.ha);return b};Ya=function(b){Xa.unregister(b.ha)};return $a(a)}var ab=void 0,bb=[];function cb(){for(;bb.length;){var a=bb.pop();a.ha.ta=!1;a["delete"]()}}function S(){}var db={};
function eb(a,b,c){if(void 0===a[b].la){var d=a[b];a[b]=function(){a[b].la.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].la+")!");return a[b].la[arguments.length].apply(this,arguments)};a[b].la=[];a[b].la[d.za]=d}}
function fb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].la&&void 0!==e[a].la[c])&&P("Cannot register public name '"+a+"' twice"),eb(e,a,a),e.hasOwnProperty(c)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].la[c]=b):(e[a]=b,void 0!==c&&(e[a].gb=c))}function gb(a,b,c,d,f,h,l,k){this.name=a;this.constructor=b;this.ua=c;this.sa=d;this.pa=f;this.Oa=h;this.ya=l;this.Ma=k;this.Sa=[]}
function hb(a,b,c){for(;b!==c;)b.ya||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ya(a),b=b.pa;return a}function ib(a,b){if(null===b)return this.Ga&&P("null is not a valid "+this.name),0;b.ha||P('Cannot pass "'+T(b)+'" as a '+this.name);b.ha.ja||P("Cannot pass deleted object as a pointer of type "+this.name);return hb(b.ha.ja,b.ha.ka.ia,this.ia)}
function jb(a,b){if(null===b){this.Ga&&P("null is not a valid "+this.name);if(this.Ba){var c=this.Ta();null!==a&&a.push(this.sa,c);return c}return 0}b.ha||P('Cannot pass "'+T(b)+'" as a '+this.name);b.ha.ja||P("Cannot pass deleted object as a pointer of type "+this.name);!this.Aa&&b.ha.ka.Aa&&P("Cannot convert argument of type "+(b.ha.oa?b.ha.oa.name:b.ha.ka.name)+" to parameter type "+this.name);c=hb(b.ha.ja,b.ha.ka.ia,this.ia);if(this.Ba)switch(void 0===b.ha.na&&P("Passing raw pointer to smart pointer is illegal"),
this.Va){case 0:b.ha.oa===this?c=b.ha.na:P("Cannot convert argument of type "+(b.ha.oa?b.ha.oa.name:b.ha.ka.name)+" to parameter type "+this.name);break;case 1:c=b.ha.na;break;case 2:if(b.ha.oa===this)c=b.ha.na;else{var d=b.clone();c=this.Ua(c,kb(function(){d["delete"]()}));null!==a&&a.push(this.sa,c)}break;default:P("Unsupporting sharing policy")}return c}
function lb(a,b){if(null===b)return this.Ga&&P("null is not a valid "+this.name),0;b.ha||P('Cannot pass "'+T(b)+'" as a '+this.name);b.ha.ja||P("Cannot pass deleted object as a pointer of type "+this.name);b.ha.ka.Aa&&P("Cannot convert argument of type "+b.ha.ka.name+" to parameter type "+this.name);return hb(b.ha.ja,b.ha.ka.ia,this.ia)}function mb(a){return this.fromWireType(I[a>>2])}function nb(a,b,c){if(b===c)return a;if(void 0===c.pa)return null;a=nb(a,b,c.pa);return null===a?null:c.Ma(a)}
var ob={};function pb(a,b){for(void 0===b&&P("ptr should not be undefined");a.pa;)b=a.ya(b),a=a.pa;return ob[b]}function qb(a,b){b.ka&&b.ja||Ua("makeClassHandle requires ptr and ptrType");!!b.oa!==!!b.na&&Ua("Both smartPtrType and smartPtr must be specified");b.count={value:1};return $a(Object.create(a,{ha:{value:b}}))}
function U(a,b,c,d){this.name=a;this.ia=b;this.Ga=c;this.Aa=d;this.Ba=!1;this.sa=this.Ua=this.Ta=this.Ka=this.Va=this.Ra=void 0;void 0!==b.pa?this.toWireType=jb:(this.toWireType=d?ib:lb,this.qa=null)}function rb(a,b,c){e.hasOwnProperty(a)||Ua("Replacing nonexistant public symbol");void 0!==e[a].la&&void 0!==c?e[a].la[c]=b:(e[a]=b,e[a].za=c)}
function X(a,b){a=L(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var sb=void 0;function tb(a){a=ub(a);var b=L(a);Y(a);return b}
function vb(a,b){function c(h){f[h]||N[h]||(Pa[h]?Pa[h].forEach(c):(d.push(h),f[h]=!0))}var d=[],f={};b.forEach(c);throw new sb(a+": "+d.map(tb).join([", "]));}function wb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}function xb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function yb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ra(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Bb(a,b,c,d,f){var h=b.length;2>h&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].qa){k=!0;break}var p="void"!==b[0].name,m="",n="";for(c=0;c<h-2;++c)m+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Qa(a)+"("+m+") {\nif (arguments.length !== "+(h-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(h-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var v=k?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[P,d,f,xb,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<h-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);l&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(p?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)h=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].qa&&(a+=h+"_dtor("+h+"); // "+b[c].name+"\n",m.push(h+"_dtor"),d.push(b[c].qa));p&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return yb(m).apply(null,d)}var Cb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Db(a){4<a&&0===--Z[a].Ha&&(Z[a]=void 0,Cb.push(a))}
function kb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Cb.length?Cb.pop():Z.length;Z[b]={Ha:1,value:a};return b}}function T(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Eb(a,b){switch(b){case 2:return function(c){return this.fromWireType(sa[c>>2])};case 3:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Fb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return ma[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Gb;Gb=function(){return performance.now()};var Hb={};
function Ib(){if(!Jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Hb)a[b]=Hb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Jb=c}return Jb}var Jb;function Kb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Lb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Mb=[31,29,31,30,31,30,31,31,30,31,30,31],Nb=[31,28,31,30,31,30,31,31,30,31,30,31];function Ob(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Kb(a.getFullYear())?Mb:Nb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Pb(a,b,c,d){function f(g,q,w){for(g="number"===typeof g?g.toString():g||"";g.length<q;)g=w[0]+g;return g}function h(g,q){return f(g,q,"0")}function l(g,q){function w(V){return 0>V?-1:0<V?1:0}var z;0===(z=w(g.getFullYear()-q.getFullYear()))&&0===(z=w(g.getMonth()-q.getMonth()))&&(z=w(g.getDate()-q.getDate()));return z}function k(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function p(g){g=Ob(new Date(g.ma+1900,0,1),g.Ea);var q=new Date(g.getFullYear()+1,0,4),w=k(new Date(g.getFullYear(),0,4));q=k(q);return 0>=l(w,g)?0>=l(q,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=F[d+40>>2];d={Ya:F[d>>2],Xa:F[d+4>>2],Ca:F[d+8>>2],xa:F[d+12>>2],va:F[d+16>>2],ma:F[d+20>>2],Da:F[d+24>>2],Ea:F[d+28>>2],hb:F[d+32>>2],Wa:F[d+
36>>2],Za:m?m?ha(D,m,void 0):"":""};c=c?ha(D,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in m)c=c.replace(new RegExp(n,"g"),m[n]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");m={"%a":function(g){return v[g.Da].substring(0,3)},"%A":function(g){return v[g.Da]},"%b":function(g){return u[g.va].substring(0,3)},"%B":function(g){return u[g.va]},"%C":function(g){return h((g.ma+1900)/100|0,2)},"%d":function(g){return h(g.xa,2)},"%e":function(g){return f(g.xa,2," ")},"%g":function(g){return p(g).toString().substring(2)},"%G":function(g){return p(g)},"%H":function(g){return h(g.Ca,
2)},"%I":function(g){g=g.Ca;0==g?g=12:12<g&&(g-=12);return h(g,2)},"%j":function(g){return h(g.xa+Lb(Kb(g.ma+1900)?Mb:Nb,g.va-1),3)},"%m":function(g){return h(g.va+1,2)},"%M":function(g){return h(g.Xa,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.Ca&&12>g.Ca?"AM":"PM"},"%S":function(g){return h(g.Ya,2)},"%t":function(){return"\t"},"%u":function(g){return g.Da||7},"%U":function(g){var q=new Date(g.ma+1900,0,1),w=0===q.getDay()?q:Ob(q,7-q.getDay());g=new Date(g.ma+1900,g.va,g.xa);return 0>
l(w,g)?h(Math.ceil((31-w.getDate()+(Lb(Kb(g.getFullYear())?Mb:Nb,g.getMonth()-1)-31)+g.getDate())/7),2):0===l(w,q)?"01":"00"},"%V":function(g){var q=new Date(g.ma+1901,0,4),w=k(new Date(g.ma+1900,0,4));q=k(q);var z=Ob(new Date(g.ma+1900,0,1),g.Ea);return 0>l(z,w)?"53":0>=l(q,z)?"01":h(Math.ceil((w.getFullYear()<g.ma+1900?g.Ea+32-w.getDate():g.Ea+1-w.getDate())/7),2)},"%w":function(g){return g.Da},"%W":function(g){var q=new Date(g.ma,0,1),w=1===q.getDay()?q:Ob(q,0===q.getDay()?1:7-q.getDay()+1);g=
new Date(g.ma+1900,g.va,g.xa);return 0>l(w,g)?h(Math.ceil((31-w.getDate()+(Lb(Kb(g.getFullYear())?Mb:Nb,g.getMonth()-1)-31)+g.getDate())/7),2):0===l(w,q)?"01":"00"},"%y":function(g){return(g.ma+1900).toString().substring(2)},"%Y":function(g){return g.ma+1900},"%z":function(g){g=g.Wa;var q=0<=g;g=Math.abs(g)/60;return(q?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.Za},"%%":function(){return"%"}};for(n in m)0<=c.indexOf(n)&&(c=c.replace(new RegExp(n,"g"),m[n](d)));n=
Qb(c);if(n.length>b)return 0;H.set(n,a);return n.length-1}for(var Rb=Array(256),Sb=0;256>Sb;++Sb)Rb[Sb]=String.fromCharCode(Sb);Oa=Rb;O=e.BindingError=Sa("BindingError");Ta=e.InternalError=Sa("InternalError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.ha.ka.ia,c=this.ha.ja,d=a.ha.ka.ia;for(a=a.ha.ja;b.pa;)c=b.ya(c),b=b.pa;for(;d.pa;)a=d.ya(a),d=d.pa;return b===d&&c===a};
S.prototype.clone=function(){this.ha.ja||Wa(this);if(this.ha.wa)return this.ha.count.value+=1,this;var a=$a(Object.create(Object.getPrototypeOf(this),{ha:{value:Va(this.ha)}}));a.ha.count.value+=1;a.ha.ta=!1;return a};S.prototype["delete"]=function(){this.ha.ja||Wa(this);this.ha.ta&&!this.ha.wa&&P("Object already scheduled for deletion");Ya(this);Za(this.ha);this.ha.wa||(this.ha.na=void 0,this.ha.ja=void 0)};S.prototype.isDeleted=function(){return!this.ha.ja};
S.prototype.deleteLater=function(){this.ha.ja||Wa(this);this.ha.ta&&!this.ha.wa&&P("Object already scheduled for deletion");bb.push(this);1===bb.length&&ab&&ab(cb);this.ha.ta=!0;return this};U.prototype.Pa=function(a){this.Ka&&(a=this.Ka(a));return a};U.prototype.Ia=function(a){this.sa&&this.sa(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=mb;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.Ba?qb(this.ia.ua,{ka:this.Ra,ja:c,oa:this,na:a}):qb(this.ia.ua,{ka:this,ja:a})}var c=this.Pa(a);if(!c)return this.Ia(a),null;var d=pb(this.ia,c);if(void 0!==d){if(0===d.ha.count.value)return d.ha.ja=c,d.ha.na=a,d.clone();d=d.clone();this.Ia(a);return d}d=this.ia.Oa(c);d=db[d];if(!d)return b.call(this);d=this.Aa?d.La:d.pointerType;var f=nb(c,this.ia,d.ia);return null===f?b.call(this):this.Ba?qb(d.ia.ua,{ka:d,ja:f,oa:this,na:a}):qb(d.ia.ua,
{ka:d,ja:f})};e.getInheritedInstanceCount=function(){return Object.keys(ob).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in ob)ob.hasOwnProperty(b)&&a.push(ob[b]);return a};e.flushPendingDeletes=cb;e.setDelayFunction=function(a){ab=a;bb.length&&ab&&ab(cb)};sb=e.UnboundTypeError=Sa("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
function Qb(a){var b=Array(ja(a)+1);ia(a,b,0,b.length);return b}
var Vb={r:function(a){return Tb(a)},q:function(a){"uncaught_exception"in Ja?Ja.Ja++:Ja.Ja=1;throw a;},x:function(){F[Ub()>>2]=63;return-1},w:function(a,b){if(-1===(a|0)||0===b)a=-28;else{var c=Ka[a];c&&b===c.eb&&(Ka[a]=null,c.$a&&Y(c.fb));a=0}return a},E:function(a,b,c,d,f){var h=Na(c);b=L(b);R(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=H;else if(2===c)k=E;else if(4===c)k=F;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(k[l>>h])},qa:null})},h:function(a,b,c,d,f,h,l,k,p,m,n,v,u){n=L(n);h=X(f,h);k&&(k=X(l,k));m&&(m=X(p,m));u=X(v,u);var g=Qa(n);fb(g,function(){vb("Cannot construct "+n+" due to unbound types",[d])});Q([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.ia;var z=w.ua}else z=S.prototype;q=Ra(g,function(){if(Object.getPrototypeOf(this)!==V)throw new O("Use 'new' to construct "+n);if(void 0===W.ra)throw new O(n+" has no accessible constructor");var zb=W.ra[arguments.length];if(void 0===
zb)throw new O("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(W.ra).toString()+") parameters instead!");return zb.apply(this,arguments)});var V=Object.create(z,{constructor:{value:q}});q.prototype=V;var W=new gb(n,q,V,u,w,h,k,m);w=new U(n,W,!0,!1);z=new U(n+"*",W,!1,!1);var Ab=new U(n+" const*",W,!1,!0);db[a]={pointerType:z,La:Ab};rb(g,q);return[w,z,Ab]})},e:function(a,b,c,d,f,h){0<b||B("Assertion failed: undefined");var l=wb(b,c);
f=X(d,f);var k=[h],p=[];Q([],[a],function(m){m=m[0];var n="constructor "+m.name;void 0===m.ia.ra&&(m.ia.ra=[]);if(void 0!==m.ia.ra[b-1])throw new O("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.ia.ra[b-1]=function(){vb("Cannot construct "+m.name+" due to unbound types",l)};Q([],l,function(v){m.ia.ra[b-1]=function(){arguments.length!==
b-1&&P(n+" called with "+arguments.length+" arguments, expected "+(b-1));p.length=0;k.length=b;for(var u=1;u<b;++u)k[u]=v[u].toWireType(p,arguments[u-1]);u=f.apply(null,k);xb(p);return v[0].fromWireType(u)};return[]});return[]})},a:function(a,b,c,d,f,h,l,k){var p=wb(c,d);b=L(b);h=X(f,h);Q([],[a],function(m){function n(){vb("Cannot call "+v+" due to unbound types",p)}m=m[0];var v=m.name+"."+b;k&&m.ia.Sa.push(b);var u=m.ia.ua,g=u[b];void 0===g||void 0===g.la&&g.className!==m.name&&g.za===c-2?(n.za=
c-2,n.className=m.name,u[b]=n):(eb(u,b,v),u[b].la[c-2]=n);Q([],p,function(q){q=Bb(v,q,m,h,l);void 0===u[b].la?(q.za=c-2,u[b]=q):u[b].la[c-2]=q;return[]});return[]})},D:function(a,b){b=L(b);R(a,{name:b,fromWireType:function(c){var d=Z[c].value;Db(c);return d},toWireType:function(c,d){return kb(d)},argPackAdvance:8,readValueFromPointer:mb,qa:null})},l:function(a,b,c){c=Na(c);b=L(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+
T(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Eb(b,c),qa:null})},i:function(a,b,c,d,f,h){var l=wb(b,c);a=L(a);f=X(d,f);fb(a,function(){vb("Cannot call "+a+" due to unbound types",l)},b-1);Q([],l,function(k){rb(a,Bb(a,[k[0],null].concat(k.slice(1)),null,f,h),b-1);return[]})},c:function(a,b,c,d,f){function h(m){return m}b=L(b);-1===f&&(f=4294967295);var l=Na(c);if(0===d){var k=32-8*c;h=function(m){return m<<k>>>k}}var p=-1!=b.indexOf("unsigned");R(a,{name:b,fromWireType:h,
toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+T(n)+'" to '+this.name);if(n<d||n>f)throw new TypeError('Passing a number "'+T(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Fb(b,l,0!==d),qa:null})},b:function(a,b,c){function d(h){h>>=2;var l=I;return new f(G,l[h+1],l[h])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Qa:!0})},m:function(a,b){b=L(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var f=I[d>>2];if(c)for(var h=d+4,l=0;l<=f;++l){var k=d+4+l;if(0==D[k]||l==f){h=h?ha(D,h,k-h):"";if(void 0===p)var p=h;else p+=String.fromCharCode(0),p+=h;h=k+1}}else{p=Array(f);for(l=0;l<f;++l)p[l]=String.fromCharCode(D[d+4+l]);p=p.join("")}Y(d);return p},toWireType:function(d,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var h="string"===typeof f;h||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||P("Cannot pass non-string to std::string");var l=(c&&h?function(){return ja(f)}:function(){return f.length})(),k=Tb(4+l+1);I[k>>2]=l;if(c&&h)ia(f,D,k+4,l+1);else if(h)for(h=0;h<l;++h){var p=f.charCodeAt(h);255<p&&(Y(k),P("String has UTF-16 code units that do not fit in 8 bits"));D[k+4+h]=p}else for(h=0;h<l;++h)D[k+4+h]=f[h];null!==d&&d.push(Y,k);return k},
argPackAdvance:8,readValueFromPointer:mb,qa:function(d){Y(d)}})},g:function(a,b,c){c=L(c);if(2===b){var d=la;var f=na;var h=oa;var l=function(){return ma};var k=1}else 4===b&&(d=pa,f=qa,h=ra,l=function(){return I},k=2);R(a,{name:c,fromWireType:function(p){for(var m=I[p>>2],n=l(),v,u=p+4,g=0;g<=m;++g){var q=p+4+g*b;if(0==n[q>>k]||g==m)u=d(u,q-u),void 0===v?v=u:(v+=String.fromCharCode(0),v+=u),u=q+b}Y(p);return v},toWireType:function(p,m){"string"!==typeof m&&P("Cannot pass non-string to C++ string type "+
c);var n=h(m),v=Tb(4+n+b);I[v>>2]=n>>k;f(m,v+4,n+b);null!==p&&p.push(Y,v);return v},argPackAdvance:8,readValueFromPointer:mb,qa:function(p){Y(p)}})},n:function(a,b){b=L(b);R(a,{cb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},o:Db,p:function(a){4<a&&(Z[a].Ha+=1)},d:function(a,b){var c=N[a];void 0===c&&P("_emval_take_value has unknown type "+tb(a));a=c.readValueFromPointer(b);return kb(a)},f:function(){B()},C:function(a,b){if(0===a)a=Date.now();else if(1===a||4===
a)a=Gb();else return F[Ub()>>2]=28,-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},t:function(a,b,c){D.copyWithin(a,b,b+c)},u:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{C.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);ua(C.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},y:function(a,b){var c=0;Ib().forEach(function(d,f){var h=b+
c;f=F[a+4*f>>2]=h;for(h=0;h<d.length;++h)H[f++>>0]=d.charCodeAt(h);H[f>>0]=0;c+=d.length+1});return 0},z:function(a,b){var c=Ib();F[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});F[b>>2]=d;return 0},B:function(){return 0},A:function(a,b,c,d){a=Ma.bb(a);b=Ma.ab(a,b,c);F[d>>2]=b;return 0},s:function(){},k:function(a,b,c,d){for(var f=0,h=0;h<c;h++){for(var l=F[b+8*h>>2],k=F[b+(8*h+4)>>2],p=0;p<k;p++){var m=D[l+p],n=La[a];0===m||10===m?((1===a?ca:y)(ha(n,0)),n.length=0):n.push(m)}f+=k}F[d>>
2]=f;return 0},memory:C,j:function(){},v:function(a,b,c,d){return Pb(a,b,c,d)},table:da};
(function(){function a(f){e.asm=f.exports;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ca&&(clearInterval(Ca),Ca=null),Da&&(f=Da,Da=null,f()))}function b(f){a(f.instance)}function c(f){return Ha().then(function(h){return WebAssembly.instantiate(h,d)}).then(f,function(h){y("failed to asynchronously prepare wasm: "+h);B(h)})}var d={a:Vb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(A||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||"function"!==typeof fetch)return c(b);fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ia=e.___wasm_call_ctors=function(){return(Ia=e.___wasm_call_ctors=e.asm.F).apply(null,arguments)},ub=e.___getTypeName=function(){return(ub=e.___getTypeName=e.asm.G).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.H).apply(null,arguments)};
var Ub=e.___errno_location=function(){return(Ub=e.___errno_location=e.asm.I).apply(null,arguments)},Tb=e._malloc=function(){return(Tb=e._malloc=e.asm.J).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.K).apply(null,arguments)};e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.L).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.M).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.N).apply(null,arguments)};
e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.O).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.P).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.Q).apply(null,arguments)};e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.R).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.S).apply(null,arguments)};e.dynCall_iiiii=function(){return(e.dynCall_iiiii=e.asm.T).apply(null,arguments)};
e.dynCall_v=function(){return(e.dynCall_v=e.asm.U).apply(null,arguments)};e.dynCall_jj=function(){return(e.dynCall_jj=e.asm.V).apply(null,arguments)};e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.W).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.X).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.Y).apply(null,arguments)};e.dynCall_iiiiii=function(){return(e.dynCall_iiiiii=e.asm.Z).apply(null,arguments)};
e.dynCall_iiiiiiiii=function(){return(e.dynCall_iiiiiiiii=e.asm._).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.$).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.aa).apply(null,arguments)};e.dynCall_iiiiid=function(){return(e.dynCall_iiiiid=e.asm.ba).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.ca).apply(null,arguments)};
e.dynCall_iiiiiiii=function(){return(e.dynCall_iiiiiiii=e.asm.da).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.ea).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.fa).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.ga).apply(null,arguments)};var Wb;Da=function Xb(){Wb||Yb();Wb||(Da=Xb)};
function Yb(){function a(){if(!Wb&&(Wb=!0,e.calledRun=!0,!ea)){wa(ya);wa(za);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Aa.unshift(b)}wa(Aa)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();wa(xa);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=Yb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Yb();e.vec=function(a){var b=new e.VecInt;b.resize(a.length,0);for(var c=0;c<a.length;c++)b.set(c,a[c]);return b};e.vec2=function(a){for(var b=new e.Vec2Int,c=0;c<a.length;c++)b.push_back(e.vec(a[c]));return b};e.vec3=function(a){for(var b=new e.Vec3Int,c=0;c<a.length;c++)b.push_back(e.vec2(a[c]));return b};
e.arr=function(a){for(var b=[],c=a.size(),d=0;d<c;d++)b.push(a.get(d));return b};e.setup=function(a){e._setup(e.vec3(a))};e.solve=function(a){return e.arr(e._solve(e.vec2(a)))};
