var e;e||(e=typeof Module !== 'undefined' ? Module : {});var p={},q;for(q in e)e.hasOwnProperty(q)&&(p[q]=e[q]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var r="";function aa(a){return e.locateFile?e.locateFile(a,r):r+a}r=self.location.href;r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"";e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.setWindowTitle=function(a){document.title=a};
var ba=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),u=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ba);for(q in p)p.hasOwnProperty(q)&&(e[q]=p[q]);p=void 0;function ca(a){var b;b||(b=16);return Math.ceil(a/b)*b}var da={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},ea=!1;
function fa(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=v[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,v.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return ha(v,a)}var ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ha(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ia)return ia.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var n=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|n}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function ja(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(2097151>=g){if(c+3>=d)break;b[c++]=240|g>>18}else{if(67108863>=g){if(c+4>=d)break;b[c++]=248|g>>24}else{if(c+5>=d)break;b[c++]=252|g>>30;b[c++]=128|g>>24&63}b[c++]=128|g>>18&63}b[c++]=128|g>>12&63}b[c++]=
128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}function ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function la(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,w,v,ma,na,x,y,oa,pa;
function qa(){e.HEAP8=w=new Int8Array(buffer);e.HEAP16=ma=new Int16Array(buffer);e.HEAP32=x=new Int32Array(buffer);e.HEAPU8=v=new Uint8Array(buffer);e.HEAPU16=na=new Uint16Array(buffer);e.HEAPU32=y=new Uint32Array(buffer);e.HEAPF32=oa=new Float32Array(buffer);e.HEAPF64=pa=new Float64Array(buffer)}var ra,z,sa,ta,ua,va,A;ra=z=sa=ta=ua=va=A=0;e.reallocBuffer||(e.reallocBuffer=function(a){try{var b=w;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(d){return!1}return wa(c)?c:!1});var xa;
try{xa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),xa(new ArrayBuffer(4))}catch(a){xa=function(b){return b.byteLength}}var ya=e.TOTAL_STACK||5242880,B=e.TOTAL_MEMORY||16777216;B<ya&&u("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+B+"! (TOTAL_STACK="+ya+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:B/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(B),e.buffer=buffer);qa();function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.F;"number"===typeof c?void 0===b.N?e.dynCall_v(c):e.dynCall_vi(c,b.N):c(void 0===b.N?null:b.N)}}}var Aa=[],Ba=[],Ca=[],Da=[],Ea=!1;function Fa(){var a=e.preRun.shift();Aa.unshift(a)}
var C=0,Ga=null,E=null;e.preloadedImages={};e.preloadedAudios={};function Ha(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(m){F(m)}}function b(){return e.wasmBinary||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){k=a.exports;if(k.memory){a=
k.memory;var b=e.buffer;a.byteLength<b.byteLength&&u("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;qa()}e.asm=k;e.usingWasm=!0;C--;e.monitorRunDependencies&&e.monitorRunDependencies(C);0==C&&(null!==Ga&&(clearInterval(Ga),Ga=null),E&&(a=E,E=null,a()))}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){u("failed to asynchronously prepare wasm: "+
a);F(a)})}if("object"!==typeof WebAssembly)return u("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return u("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;C++;e.monitorRunDependencies&&e.monitorRunDependencies(C);if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(Bb){return u("Module.instantiateWasm callback failed with error: "+Bb),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Ha(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,function(a){u("wasm streaming compile failed: "+a);u("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="puzzle.wast",f="puzzle.wasm",g="puzzle.temp.asm.js";Ha(d)||(d=aa(d));Ha(f)||(f=aa(f));Ha(g)||(g=aa(g));var h={global:null,env:null,asm2wasm:da,parent:e},k=null;e.asmPreload=e.asm;var n=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===l)var b=n(a);else a:{a=
la(a,e.usingWasm?65536:16777216);var c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(D){b=null;break a}b=void 0}return b};var l="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):
Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||F("Assertion failed: no binaryen method succeeded.");return b}})();ra=1024;z=ra+30720;Ba.push({F:function(){Ia()}},{F:function(){Ja()}},{F:function(){Ka()}},{F:function(){La()}},{F:function(){Ma()}});e.STATIC_BASE=ra;e.STATIC_BUMP=30720;z+=16;function Na(a){e.___errno_location&&(x[e.___errno_location()>>2]=a);return a}var Oa=[null,[],[]],G=0;function H(){G+=4;return x[G-4>>2]}var I={};
function Pa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Qa=void 0;function J(a){for(var b="";v[a];)b+=Qa[v[a++]];return b}var K={},L={},Ra={};function Sa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ta(a,b){a=Sa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ua(a){var b=Error,c=Ta(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var M=void 0;function N(a){throw new M(a);}var Va=void 0;function Wa(a){throw new Va(a);}function O(a,b,c){function d(b){b=c(b);b.length!==a.length&&Wa("Mismatched type converter count");for(var d=0;d<a.length;++d)P(a[d],b[d])}a.forEach(function(a){Ra[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){L.hasOwnProperty(a)?f[b]=L[a]:(g.push(a),K.hasOwnProperty(a)||(K[a]=[]),K[a].push(function(){f[b]=L[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function P(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||N('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.fa)return;N("Cannot register type '"+d+"' twice")}L[a]=b;delete Ra[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(function(a){a()}))}function Xa(a){N(a.a.f.b.name+" instance already deleted")}var Q=void 0,S=[];
function Ya(){for(;S.length;){var a=S.pop();a.a.A=!1;a["delete"]()}}function T(){}var Za={};function $a(a,b,c){if(void 0===a[b].h){var d=a[b];a[b]=function(){a[b].h.hasOwnProperty(arguments.length)||N("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].h+")!");return a[b].h[arguments.length].apply(this,arguments)};a[b].h=[];a[b].h[d.I]=d}}
function ab(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].h&&void 0!==e[a].h[c])&&N("Cannot register public name '"+a+"' twice"),$a(e,a,a),e.hasOwnProperty(c)&&N("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].h[c]=b):(e[a]=b,void 0!==c&&(e[a].Ha=c))}function bb(a,b,c,d,f,g,h,k){this.name=a;this.constructor=b;this.B=c;this.v=d;this.m=f;this.ba=g;this.H=h;this.aa=k;this.ia=[]}
function cb(a,b,c){for(;b!==c;)b.H||N("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.H(a),b=b.m;return a}function db(a,b){if(null===b)return this.O&&N("null is not a valid "+this.name),0;b.a||N('Cannot pass "'+U(b)+'" as a '+this.name);b.a.c||N("Cannot pass deleted object as a pointer of type "+this.name);return cb(b.a.c,b.a.f.b,this.b)}
function eb(a,b){if(null===b){this.O&&N("null is not a valid "+this.name);if(this.K){var c=this.ka();null!==a&&a.push(this.v,c);return c}return 0}b.a||N('Cannot pass "'+U(b)+'" as a '+this.name);b.a.c||N("Cannot pass deleted object as a pointer of type "+this.name);!this.J&&b.a.f.J&&N("Cannot convert argument of type "+(b.a.l?b.a.l.name:b.a.f.name)+" to parameter type "+this.name);c=cb(b.a.c,b.a.f.b,this.b);if(this.K)switch(void 0===b.a.j&&N("Passing raw pointer to smart pointer is illegal"),this.ma){case 0:b.a.l===
this?c=b.a.j:N("Cannot convert argument of type "+(b.a.l?b.a.l.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:c=b.a.j;break;case 2:if(b.a.l===this)c=b.a.j;else{var d=b.clone();c=this.la(c,fb(function(){d["delete"]()}));null!==a&&a.push(this.v,c)}break;default:N("Unsupporting sharing policy")}return c}
function gb(a,b){if(null===b)return this.O&&N("null is not a valid "+this.name),0;b.a||N('Cannot pass "'+U(b)+'" as a '+this.name);b.a.c||N("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.J&&N("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return cb(b.a.c,b.a.f.b,this.b)}function hb(a){return this.fromWireType(y[a>>2])}function ib(a,b,c){if(b===c)return a;if(void 0===c.m)return null;a=ib(a,b,c.m);return null===a?null:c.aa(a)}var jb={};
function kb(a,b){for(void 0===b&&N("ptr should not be undefined");a.m;)b=a.H(b),a=a.m;return jb[b]}function lb(a,b){b.f&&b.c||Wa("makeClassHandle requires ptr and ptrType");!!b.l!==!!b.j&&Wa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{a:{value:b}})}
function V(a,b,c,d,f,g,h,k,n,l,m){this.name=a;this.b=b;this.O=c;this.J=d;this.K=f;this.ha=g;this.ma=h;this.U=k;this.ka=n;this.la=l;this.v=m;f||void 0!==b.m?this.toWireType=eb:(this.toWireType=d?db:gb,this.o=null)}function mb(a,b,c){e.hasOwnProperty(a)||Wa("Replacing nonexistant public symbol");void 0!==e[a].h&&void 0!==c?e[a].h[c]=b:(e[a]=b,e[a].I=c)}
function W(a,b){a=J(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e.asm["dynCall_"+a];void 0===c&&(c=e.asm["dynCall_"+a.replace(/f/g,"d")],void 0===c&&N("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall",
"rawFunction",f+"};\n"))(c,b)}"function"!==typeof c&&N("unknown function pointer with signature "+a+": "+b);return c}var nb=void 0;function ob(a){a=pb(a);var b=J(a);X(a);return b}function qb(a,b){function c(a){f[a]||L[a]||(Ra[a]?Ra[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new nb(a+": "+d.map(ob).join([", "]));}function rb(a,b){for(var c=[],d=0;d<a;d++)c.push(x[(b>>2)+d]);return c}function sb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function tb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ta(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ub(a,b,c,d,f){var g=b.length;2>g&&N("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].o){k=!0;break}var n="void"!==b[0].name,l="",m="";for(c=0;c<g-2;++c)l+=(0!==c?", ":"")+"arg"+c,m+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Sa(a)+"("+l+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var t=k?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[N,d,f,sb,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",l.push("argType"+c),d.push(b[c+2]);h&&(m="thisWired"+(0<m.length?", ":"")+m);a+=(n?"var rv = ":"")+"invoker(fn"+(0<m.length?", ":"")+m+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].o&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",l.push(g+"_dtor"),d.push(b[c].o));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(a+"}\n");return tb(l).apply(null,d)}var vb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function wb(a){4<a&&0===--Y[a].P&&(Y[a]=void 0,vb.push(a))}
function fb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=vb.length?vb.pop():Y.length;Y[b]={P:1,value:a};return b}}function U(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function xb(a,b){switch(b){case 2:return function(a){return this.fromWireType(oa[a>>2])};case 3:return function(a){return this.fromWireType(pa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function yb(a,b,c){switch(b){case 0:return c?function(a){return w[a]}:function(a){return v[a]};case 1:return c?function(a){return ma[a>>1]}:function(a){return na[a>>1]};case 2:return c?function(a){return x[a>>2]}:function(a){return y[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function zb(){F()}var Ab={};function Cb(a){if(0===a)return 0;a=fa(a);if(!Ab.hasOwnProperty(a))return 0;Cb.i&&X(Cb.i);a=Ab[a];var b=ka(a)+1,c=Db(b);c&&ja(a,w,c,b);Cb.i=c;return Cb.i}
function Z(){Z.i||(Z.i=[]);Z.i.push(Eb());return Z.i.length-1}var Fb={},Gb=1;function Hb(a,b){Hb.i||(Hb.i={});a in Hb.i||(e.dynCall_v(b),Hb.i[a]=1)}function Ib(a){return 0===a%4&&(0!==a%100||0===a%400)}function Jb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Kb=[31,29,31,30,31,30,31,31,30,31,30,31],Lb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Mb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ib(a.getFullYear())?Kb:Lb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Nb(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function k(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function n(a){a=Mb(new Date(a.g+1900,0,1),a.M);var b=k(new Date(a.getFullYear()+1,0,4));return 0>=h(k(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var l=x[d+40>>2];d={pa:x[d>>2],oa:x[d+4>>2],L:x[d+8>>2],w:x[d+12>>2],s:x[d+16>>2],g:x[d+20>>2],V:x[d+24>>2],M:x[d+28>>2],Ka:x[d+32>>2],na:x[d+36>>2],qa:l?fa(l):
""};c=fa(c);l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var m in l)c=c.replace(new RegExp(m,"g"),l[m]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),R="January February March April May June July August September October November December".split(" ");l={"%a":function(a){return t[a.V].substring(0,3)},"%A":function(a){return t[a.V]},"%b":function(a){return R[a.s].substring(0,
3)},"%B":function(a){return R[a.s]},"%C":function(a){return g((a.g+1900)/100|0,2)},"%d":function(a){return g(a.w,2)},"%e":function(a){return f(a.w,2," ")},"%g":function(a){return n(a).toString().substring(2)},"%G":function(a){return n(a)},"%H":function(a){return g(a.L,2)},"%I":function(a){a=a.L;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.w+Jb(Ib(a.g+1900)?Kb:Lb,a.s-1),3)},"%m":function(a){return g(a.s+1,2)},"%M":function(a){return g(a.oa,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.L&&12>a.L?"AM":"PM"},"%S":function(a){return g(a.pa,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.g+1900,a.s+1,a.w,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.g+1900,0,1),c=0===b.getDay()?b:Mb(b,7-b.getDay());a=new Date(a.g+1900,a.s,a.w);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Jb(Ib(a.getFullYear())?Kb:Lb,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=k(new Date(a.g+1900,0,4)),c=k(new Date(a.g+1901,0,4)),d=Mb(new Date(a.g+
1900,0,1),a.M);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.g+1900?a.M+32-b.getDate():a.M+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.g+1900,a.s+1,a.w,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.g,0,1),c=1===b.getDay()?b:Mb(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.g+1900,a.s,a.w);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Jb(Ib(a.getFullYear())?Kb:Lb,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.g+1900).toString().substring(2)},
"%Y":function(a){return a.g+1900},"%z":function(a){a=a.na;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.qa},"%%":function(){return"%"}};for(m in l)0<=c.indexOf(m)&&(c=c.replace(new RegExp(m,"g"),l[m](d)));m=Ob(c);if(m.length>b)return 0;w.set(m,a);return m.length-1}for(var Pb=Array(256),Qb=0;256>Qb;++Qb)Pb[Qb]=String.fromCharCode(Qb);Qa=Pb;M=e.BindingError=Ua("BindingError");Va=e.InternalError=Ua("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.a.f.b,c=this.a.c,d=a.a.f.b;for(a=a.a.c;b.m;)c=b.H(c),b=b.m;for(;d.m;)a=d.H(a),d=d.m;return b===d&&c===a};T.prototype.clone=function(){this.a.c||Xa(this);if(this.a.G)return this.a.count.value+=1,this;var a=this.a;a=Object.create(Object.getPrototypeOf(this),{a:{value:{count:a.count,A:a.A,G:a.G,c:a.c,f:a.f,j:a.j,l:a.l}}});a.a.count.value+=1;a.a.A=!1;return a};
T.prototype["delete"]=function(){this.a.c||Xa(this);this.a.A&&!this.a.G&&N("Object already scheduled for deletion");--this.a.count.value;if(0===this.a.count.value){var a=this.a;a.j?a.l.v(a.j):a.f.b.v(a.c)}this.a.G||(this.a.j=void 0,this.a.c=void 0)};T.prototype.isDeleted=function(){return!this.a.c};T.prototype.deleteLater=function(){this.a.c||Xa(this);this.a.A&&!this.a.G&&N("Object already scheduled for deletion");S.push(this);1===S.length&&Q&&Q(Ya);this.a.A=!0;return this};
V.prototype.da=function(a){this.U&&(a=this.U(a));return a};V.prototype.S=function(a){this.v&&this.v(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=hb;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.K?lb(this.b.B,{f:this.ha,c:c,l:this,j:a}):lb(this.b.B,{f:this,c:a})}var c=this.da(a);if(!c)return this.S(a),null;var d=kb(this.b,c);if(void 0!==d){if(0===d.a.count.value)return d.a.c=c,d.a.j=a,d.clone();d=d.clone();this.S(a);return d}d=this.b.ba(c);d=Za[d];if(!d)return b.call(this);d=this.J?d.$:d.pointerType;var f=ib(c,this.b,d.b);return null===f?b.call(this):this.K?lb(d.b.B,{f:d,c:f,l:this,j:a}):lb(d.b.B,{f:d,c:f})};
e.getInheritedInstanceCount=function(){return Object.keys(jb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in jb)jb.hasOwnProperty(b)&&a.push(jb[b]);return a};e.flushPendingDeletes=Ya;e.setDelayFunction=function(a){Q=a;S.length&&Q&&Q(Ya)};nb=e.UnboundTypeError=Ua("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
"undefined"!==typeof dateNow?zb=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?zb=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?zb=function(){return performance.now()}:zb=Date.now;var Rb=z;z=z+4+15&-16;A=Rb;sa=ta=ca(z);ua=sa+ya;va=ca(ua);x[A>>2]=va;function Ob(a){var b=Array(ka(a)+1);ja(a,b,0,b.length);return b}e.wasmTableSize=884;e.wasmMaxTableSize=884;e.Y={};
e.Z={abort:F,enlargeMemory:function(){var a=e.usingWasm?65536:16777216,b=2147483648-a;if(x[A>>2]>b)return!1;var c=B;for(B=Math.max(B,16777216);B<x[A>>2];)536870912>=B?B=la(2*B,a):B=Math.min(la((3*B+2147483648)/4,a),b);a=e.reallocBuffer(B);if(!a||a.byteLength!=B)return B=c,!1;e.buffer=buffer=a;qa();return!0},getTotalMemory:function(){return B},abortOnCannotGrowMemory:function(){F("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+B+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___cxa_allocate_exception:function(a){return Db(a)},___cxa_throw:function(a){"uncaught_exception"in Sb?Sb.R++:Sb.R=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___cxa_uncaught_exception:function(){return!!Sb.R},___lock:function(){},___map_file:function(){Na(1);return-1},___setErrNo:Na,___syscall140:function(a,b){G=b;try{var c=I.T();H();var d=H(),f=H(),g=H();FS.Ea(c,d,g);x[f>>
2]=c.position;c.ea&&0===d&&0===g&&(c.ea=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.C||F(h),-h.D}},___syscall145:function(a,b){G=b;try{var c=I.T(),d=H(),f=H();return I.Aa(c,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.C||F(g),-g.D}},___syscall146:function(a,b){G=b;try{var c=H(),d=H(),f=H();for(b=a=0;b<f;b++){for(var g=x[d+8*b>>2],h=x[d+(8*b+4)>>2],k=0;k<h;k++){var n=c,l=v[g+k],m=Oa[n];m||F("Assertion failed: undefined");0===l||10===l?((1===n?ba:u)(ha(m,0)),
m.length=0):m.push(l)}a+=h}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.C||F(t),-t.D}},___syscall221:function(a,b){G=b;return 0},___syscall5:function(a,b){G=b;try{var c=fa(H()),d=H(),f=H();return FS.open(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof FS.C||F(g),-g.D}},___syscall54:function(a,b){G=b;return 0},___syscall6:function(a,b){G=b;try{var c=I.T();FS.close(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.C||F(d),-d.D}},___syscall91:function(a,
b){G=b;try{var c=H(),d=H(),f=I.ga[c];if(!f)return 0;if(d===f.Da){var g=FS.Ba(f.fd);I.za(c,g,d,f.flags);FS.Ga(g);I.ga[c]=null;f.ya&&X(f.Fa)}return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.C||F(h),-h.D}},___unlock:function(){},__embind_register_bool:function(a,b,c,d,f){var g=Pa(c);b=J(b);P(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=w;else if(2===c)d=ma;else if(4===c)d=x;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(d[a>>g])},o:null})},__embind_register_class:function(a,b,c,d,f,g,h,k,n,l,m,t,R){m=J(m);g=W(f,g);k&&(k=W(h,k));l&&(l=W(n,l));R=W(t,R);var D=Sa(m);ab(D,function(){qb("Cannot construct "+m+" due to unbound types",[d])});O([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.b;var f=c.B}else f=T.prototype;b=Ta(D,function(){if(Object.getPrototypeOf(this)!==h)throw new M("Use 'new' to construct "+m);if(void 0===n.u)throw new M(m+" has no accessible constructor");var a=n.u[arguments.length];
if(void 0===a)throw new M("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(n.u).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var n=new bb(m,b,h,R,c,g,k,l);c=new V(m,n,!0,!1,!1);f=new V(m+"*",n,!1,!1,!1);var t=new V(m+" const*",n,!1,!0,!1);Za[a]={pointerType:f,$:t};mb(D,b);return[c,f,t]})},__embind_register_class_constructor:function(a,b,c,d,f,g){var h=
rb(b,c);f=W(d,f);O([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.b.u&&(a.b.u=[]);if(void 0!==a.b.u[b-1])throw new M("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.b.u[b-1]=function(){qb("Cannot construct "+a.name+" due to unbound types",h)};O([],h,function(d){a.b.u[b-1]=function(){arguments.length!==b-1&&N(c+" called with "+
arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var k=1;k<b;++k)h[k]=d[k].toWireType(a,arguments[k-1]);h=f.apply(null,h);sb(a);return d[0].fromWireType(h)};return[]});return[]})},__embind_register_class_function:function(a,b,c,d,f,g,h,k){var n=rb(c,d);b=J(b);g=W(f,g);O([],[a],function(a){function d(){qb("Cannot call "+f+" due to unbound types",n)}a=a[0];var f=a.name+"."+b;k&&a.b.ia.push(b);var l=a.b.B,D=l[b];void 0===D||void 0===D.h&&D.className!==a.name&&D.I===c-2?
(d.I=c-2,d.className=a.name,l[b]=d):($a(l,b,f),l[b].h[c-2]=d);O([],n,function(d){d=ub(f,d,a,g,h);void 0===l[b].h?(d.I=c-2,l[b]=d):l[b].h[c-2]=d;return[]});return[]})},__embind_register_emval:function(a,b){b=J(b);P(a,{name:b,fromWireType:function(a){var b=Y[a].value;wb(a);return b},toWireType:function(a,b){return fb(b)},argPackAdvance:8,readValueFromPointer:hb,o:null})},__embind_register_float:function(a,b,c){c=Pa(c);b=J(b);P(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==
typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+U(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:xb(b,c),o:null})},__embind_register_function:function(a,b,c,d,f,g){var h=rb(b,c);a=J(a);f=W(d,f);ab(a,function(){qb("Cannot call "+a+" due to unbound types",h)},b-1);O([],h,function(c){c=[c[0],null].concat(c.slice(1));mb(a,ub(a,c,null,f,g),b-1);return[]})},__embind_register_integer:function(a,b,c,d,f){function g(a){return a}b=J(b);-1===f&&(f=4294967295);var h=
Pa(c);if(0===d){var k=32-8*c;g=function(a){return a<<k>>>k}}var n=-1!=b.indexOf("unsigned");P(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+U(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+U(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return n?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:yb(b,h,0!==d),o:null})},
__embind_register_memory_view:function(a,b,c){function d(a){a>>=2;var b=y;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=J(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{fa:!0})},__embind_register_std_string:function(a,b){b=J(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(a){var b=y[a>>2];if(c){var d=v[a+4+b],h=0;0!=d&&(h=d,v[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var n=
a+4+d;if(0==v[n]){k=ha(v,k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),l+=k;k=n+1}}0!=h&&(v[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(v[a+4+d]);l=l.join("")}X(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||N("Cannot pass non-string to std::string");var f=(c&&d?function(){return ka(b)}:function(){return b.length})(),
k=Db(4+f+1);y[k>>2]=f;if(c&&d)ja(b,v,k+4,f+1);else if(d)for(d=0;d<f;++d){var n=b.charCodeAt(d);255<n&&(X(k),N("String has UTF-16 code units that do not fit in 8 bits"));v[k+4+d]=n}else for(d=0;d<f;++d)v[k+4+d]=b[d];null!==a&&a.push(X,k);return k},argPackAdvance:8,readValueFromPointer:hb,o:function(a){X(a)}})},__embind_register_std_wstring:function(a,b,c){c=J(c);if(2===b){var d=function(){return na};var f=1}else 4===b&&(d=function(){return y},f=2);P(a,{name:c,fromWireType:function(a){for(var b=d(),
c=y[a>>2],g=Array(c),l=a+4>>f,m=0;m<c;++m)g[m]=String.fromCharCode(b[l+m]);X(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,l=Db(4+h*b);y[l>>2]=h;for(var m=l+4>>f,t=0;t<h;++t)g[m+t]=c.charCodeAt(t);null!==a&&a.push(X,l);return l},argPackAdvance:8,readValueFromPointer:hb,o:function(a){X(a)}})},__embind_register_void:function(a,b){b=J(b);P(a,{Ca:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},__emval_decref:wb,__emval_incref:function(a){4<a&&(Y[a].P+=
1)},__emval_take_value:function(a,b){var c=L[a];void 0===c&&N("_emval_take_value has unknown type "+ob(a));a=c.readValueFromPointer(b);return fb(a)},_abort:function(){e.abort()},_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&("undefined"!==typeof dateNow||self.performance&&self.performance.now))a=zb();else return Na(22),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_memcpy_big:function(a,b,c){v.set(v.subarray(b,b+c),a);return a},_getenv:Cb,_llvm_stackrestore:function(a){var b=
Z.i[a];Z.i.splice(a,1);Tb(b)},_llvm_stacksave:Z,_pthread_cond_wait:function(){return 0},_pthread_getspecific:function(a){return Fb[a]||0},_pthread_key_create:function(a){if(0==a)return 22;x[a>>2]=Gb;Fb[Gb]=0;Gb++;return 0},_pthread_once:Hb,_pthread_setspecific:function(a,b){if(!(a in Fb))return 22;Fb[a]=b;return 0},_strftime_l:function(a,b,c,d){return Nb(a,b,c,d)},DYNAMICTOP_PTR:A,STACKTOP:ta};var Ub=e.asm(e.Y,e.Z,buffer);e.asm=Ub;
var Ia=e.__GLOBAL__I_000101=function(){return e.asm.__GLOBAL__I_000101.apply(null,arguments)},Ka=e.__GLOBAL__sub_I_Board_cpp=function(){return e.asm.__GLOBAL__sub_I_Board_cpp.apply(null,arguments)},La=e.__GLOBAL__sub_I_bind_cpp=function(){return e.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)},Ma=e.__GLOBAL__sub_I_iostream_cpp=function(){return e.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)},Ja=e.__GLOBAL__sub_I_wasm_cpp=function(){return e.asm.__GLOBAL__sub_I_wasm_cpp.apply(null,arguments)},
Sb=e.__ZSt18uncaught_exceptionv=function(){return e.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)},pb=e.___getTypeName=function(){return e.asm.___getTypeName.apply(null,arguments)},wa=e._emscripten_replace_memory=function(){return e.asm._emscripten_replace_memory.apply(null,arguments)},X=e._free=function(){return e.asm._free.apply(null,arguments)},Db=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},Tb=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},
Eb=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.dynCall_i=function(){return e.asm.dynCall_i.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_iiiii=function(){return e.asm.dynCall_iiiii.apply(null,arguments)};
e.dynCall_iiiiid=function(){return e.asm.dynCall_iiiiid.apply(null,arguments)};e.dynCall_iiiiii=function(){return e.asm.dynCall_iiiiii.apply(null,arguments)};e.dynCall_iiiiiid=function(){return e.asm.dynCall_iiiiiid.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.dynCall_iiiiiii.apply(null,arguments)};e.dynCall_iiiiiiii=function(){return e.asm.dynCall_iiiiiiii.apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return e.asm.dynCall_iiiiiiiii.apply(null,arguments)};
e.dynCall_iiiiij=function(){return e.asm.dynCall_iiiiij.apply(null,arguments)};e.dynCall_jj=function(){return e.asm.dynCall_jj.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};
e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.dynCall_viiiii.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.dynCall_viiiiii.apply(null,arguments)};e.dynCall_viijii=function(){return e.asm.dynCall_viijii.apply(null,arguments)};e.asm=Ub;E=function Vb(){e.calledRun||Wb();e.calledRun||(E=Vb)};
function Wb(){function a(){if(!e.calledRun&&(e.calledRun=!0,!ea)){Ea||(Ea=!0,za(Ba));za(Ca);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Da.unshift(a)}za(Da)}}if(!(0<C)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fa();za(Aa);0<C||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Wb;function F(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ba(a),u(a),a=JSON.stringify(a)):a="";ea=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=F;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;Wb();e.ra=function(a){var b=new e.va;b.resize(a.length,0);for(var c=0;c<a.length;c++)b.set(c,a[c]);return b};
e.W=function(a){for(var b=new e.ta,c=0;c<a.length;c++)b.ja(e.ra(a[c]));return b};e.sa=function(a){for(var b=new e.ua,c=0;c<a.length;c++)b.ja(e.W(a[c]));return b};e.X=function(a){for(var b=[],c=a.size(),d=0;d<c;d++)b.push(a.get(d));return b};e.Ia=function(a){e.wa(e.sa(a))};e.Ja=function(a){return e.X(e.xa(e.W(a)))};
