
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var r={},t;for(t in e)e.hasOwnProperty(t)&&(r[t]=e[t]);var aa="./this.program",x="",ba;x=self.location.href;x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"";ba=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var ca=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(e[t]=r[t]);
r=null;e.thisProgram&&(aa=e.thisProgram);var da;e.wasmBinary&&(da=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,ea=!1,fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&fa)return fa.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d}function C(a,b){return a?ha(D,a,b):""}
function ia(a,b,c,d){if(0<d){d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0}}
function ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function la(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ma[c];)++c;c<<=1;if(32<c-a&&ka)return ka.decode(D.subarray(a,c));c=0;for(d="";;){var g=E[a+2*c>>1];if(0==g||c==b/2)return d;++c;d+=String.fromCharCode(g)}}
function na(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var g=0;g<c;++g)E[b>>1]=a.charCodeAt(g),b+=2;E[b>>1]=0;return b-d}function oa(a){return 2*a.length}function pa(a,b){for(var c=0,d="";!(c>=b/4);){var g=F[a+4*c>>2];if(0==g)break;++c;65536<=g?(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023)):d+=String.fromCharCode(g)}return d}
function qa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}F[b>>2]=h;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,H,D,E,ma,F,I,sa,ta;
function ua(a){G=a;e.HEAP8=H=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=ma=new Uint16Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=sa=new Float32Array(a);e.HEAPF64=ta=new Float64Array(a)}var va=e.INITIAL_MEMORY||16777216;e.wasmMemory?B=e.wasmMemory:B=new WebAssembly.Memory({initial:va/65536,maximum:32768});B&&(G=B.buffer);va=G.byteLength;ua(G);var wa,xa=[],ya=[],za=[],Aa=[];
function Ba(){var a=e.preRun.shift();xa.unshift(a)}var J=0,Ca=null,Da=null;e.preloadedImages={};e.preloadedAudios={};function A(a){if(e.onAbort)e.onAbort(a);y(a);ea=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ea(){var a=K;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var K="puzzle.wasm";
if(!Ea()){var Fa=K;K=e.locateFile?e.locateFile(Fa,x):x+Fa}function Ga(){try{if(da)return new Uint8Array(da);if(ba)return ba(K);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}function Ha(){return da||"function"!==typeof fetch?Promise.resolve().then(Ga):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ga()})}
function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.wa;"number"===typeof c?void 0===b.oa?wa.get(c)():wa.get(c)(b.oa):c(void 0===b.oa?null:b.oa)}}}function Ja(a){this.S=a-16;this.Ja=function(b){F[this.S+8>>2]=b};this.Ga=function(b){F[this.S+0>>2]=b};this.Ha=function(){F[this.S+4>>2]=0};this.Fa=function(){H[this.S+12>>0]=0};this.Ia=function(){H[this.S+13>>0]=0};this.Aa=function(b,c){this.Ja(b);this.Ga(c);this.Ha();this.Fa();this.Ia()}}
function Ka(){return 0<Ka.ta}function La(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ma=void 0;function L(a){for(var b="";D[a];)b+=Ma[D[a++]];return b}var M={},N={},Na={};function Oa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Pa(a,b){a=Oa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Qa(a){var b=Error,c=Pa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var O=void 0;function P(a){throw new O(a);}var Ra=void 0;function Sa(a){throw new Ra(a);}function Q(a,b,c){function d(k){k=c(k);k.length!==a.length&&Sa("Mismatched type converter count");for(var p=0;p<a.length;++p)R(a[p],k[p])}a.forEach(function(k){Na[k]=b});var g=Array(b.length),h=[],l=0;b.forEach(function(k,p){N.hasOwnProperty(k)?g[p]=N[k]:(h.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(function(){g[p]=N[k];++l;l===h.length&&d(g)}))});0===h.length&&d(g)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(N.hasOwnProperty(a)){if(c.za)return;P("Cannot register type '"+d+"' twice")}N[a]=b;delete Na[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(g){g()}))}function Ta(a){return{count:a.count,ca:a.ca,fa:a.fa,S:a.S,U:a.U,X:a.X,Y:a.Y}}
function Ua(a){P(a.R.U.T.name+" instance already deleted")}var Va=!1;function Wa(){}function Xa(a){--a.count.value;0===a.count.value&&(a.X?a.Y.ba(a.X):a.U.T.ba(a.S))}function Ya(a){if("undefined"===typeof FinalizationGroup)return Ya=function(b){return b},a;Va=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.S?Xa(c):console.warn("object already deleted: "+c.S)});Ya=function(b){Va.register(b,b.R,b.R);return b};Wa=function(b){Va.unregister(b.R)};return Ya(a)}
var Za=void 0,$a=[];function ab(){for(;$a.length;){var a=$a.pop();a.R.ca=!1;a["delete"]()}}function S(){}var bb={};function cb(a,b,c){if(void 0===a[b].V){var d=a[b];a[b]=function(){a[b].V.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].V+")!");return a[b].V[arguments.length].apply(this,arguments)};a[b].V=[];a[b].V[d.ia]=d}}
function db(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].V&&void 0!==e[a].V[c])&&P("Cannot register public name '"+a+"' twice"),cb(e,a,a),e.hasOwnProperty(c)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].V[c]=b):(e[a]=b,void 0!==c&&(e[a].Sa=c))}function eb(a,b,c,d,g,h,l,k){this.name=a;this.constructor=b;this.da=c;this.ba=d;this.Z=g;this.xa=h;this.ha=l;this.va=k;this.Ca=[]}
function fb(a,b,c){for(;b!==c;)b.ha||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ha(a),b=b.Z;return a}function gb(a,b){if(null===b)return this.pa&&P("null is not a valid "+this.name),0;b.R||P('Cannot pass "'+T(b)+'" as a '+this.name);b.R.S||P("Cannot pass deleted object as a pointer of type "+this.name);return fb(b.R.S,b.R.U.T,this.T)}
function hb(a,b){if(null===b){this.pa&&P("null is not a valid "+this.name);if(this.ka){var c=this.Da();null!==a&&a.push(this.ba,c);return c}return 0}b.R||P('Cannot pass "'+T(b)+'" as a '+this.name);b.R.S||P("Cannot pass deleted object as a pointer of type "+this.name);!this.ja&&b.R.U.ja&&P("Cannot convert argument of type "+(b.R.Y?b.R.Y.name:b.R.U.name)+" to parameter type "+this.name);c=fb(b.R.S,b.R.U.T,this.T);if(this.ka)switch(void 0===b.R.X&&P("Passing raw pointer to smart pointer is illegal"),
this.Ka){case 0:b.R.Y===this?c=b.R.X:P("Cannot convert argument of type "+(b.R.Y?b.R.Y.name:b.R.U.name)+" to parameter type "+this.name);break;case 1:c=b.R.X;break;case 2:if(b.R.Y===this)c=b.R.X;else{var d=b.clone();c=this.Ea(c,ib(function(){d["delete"]()}));null!==a&&a.push(this.ba,c)}break;default:P("Unsupporting sharing policy")}return c}
function jb(a,b){if(null===b)return this.pa&&P("null is not a valid "+this.name),0;b.R||P('Cannot pass "'+T(b)+'" as a '+this.name);b.R.S||P("Cannot pass deleted object as a pointer of type "+this.name);b.R.U.ja&&P("Cannot convert argument of type "+b.R.U.name+" to parameter type "+this.name);return fb(b.R.S,b.R.U.T,this.T)}function kb(a){return this.fromWireType(I[a>>2])}function lb(a,b,c){if(b===c)return a;if(void 0===c.Z)return null;a=lb(a,b,c.Z);return null===a?null:c.va(a)}var mb={};
function nb(a,b){for(void 0===b&&P("ptr should not be undefined");a.Z;)b=a.ha(b),a=a.Z;return mb[b]}function ob(a,b){b.U&&b.S||Sa("makeClassHandle requires ptr and ptrType");!!b.Y!==!!b.X&&Sa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ya(Object.create(a,{R:{value:b}}))}
function U(a,b,c,d){this.name=a;this.T=b;this.pa=c;this.ja=d;this.ka=!1;this.ba=this.Ea=this.Da=this.sa=this.Ka=this.Ba=void 0;void 0!==b.Z?this.toWireType=hb:(this.toWireType=d?gb:jb,this.$=null)}function pb(a,b,c){e.hasOwnProperty(a)||Sa("Replacing nonexistant public symbol");void 0!==e[a].V&&void 0!==c?e[a].V[c]=b:(e[a]=b,e[a].ia=c)}
function qb(a,b){0<=a.indexOf("j")||A("Assertion failed: getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var g;-1!=a.indexOf("j")?g=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):g=wa.get(b).apply(null,c);return g}}
function V(a,b){a=L(a);var c=-1!=a.indexOf("j")?qb(a,b):wa.get(b);"function"!==typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var rb=void 0;function sb(a){a=tb(a);var b=L(a);W(a);return b}function ub(a,b){function c(h){g[h]||N[h]||(Na[h]?Na[h].forEach(c):(d.push(h),g[h]=!0))}var d=[],g={};b.forEach(c);throw new rb(a+": "+d.map(sb).join([", "]));}function vb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function wb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function xb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Pa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ab(a,b,c,d,g){var h=b.length;2>h&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].$){k=!0;break}var p="void"!==b[0].name,m="",n="";for(c=0;c<h-2;++c)m+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Oa(a)+"("+m+") {\nif (arguments.length !== "+(h-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(h-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var v=k?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[P,d,g,wb,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<h-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);l&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(p?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)h=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].$&&(a+=h+"_dtor("+h+"); // "+b[c].name+"\n",m.push(h+"_dtor"),d.push(b[c].$));p&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return xb(m).apply(null,d)}var Bb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Cb(a){4<a&&0===--Z[a].qa&&(Z[a]=void 0,Bb.push(a))}
function ib(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Bb.length?Bb.pop():Z.length;Z[b]={qa:1,value:a};return b}}function T(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Db(a,b){switch(b){case 2:return function(c){return this.fromWireType(sa[c>>2])};case 3:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Eb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return ma[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Fb;Fb=function(){return performance.now()};var Gb={};
function Hb(){if(!Ib){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Gb)a[b]=Gb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ib=c}return Ib}var Ib,Jb=[null,[],[]],Kb={};function Lb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Mb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Nb=[31,29,31,30,31,30,31,31,30,31,30,31],Ob=[31,28,31,30,31,30,31,31,30,31,30,31];function Pb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Lb(a.getFullYear())?Nb:Ob)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Qb(a,b,c,d){function g(f,q,w){for(f="number"===typeof f?f.toString():f||"";f.length<q;)f=w[0]+f;return f}function h(f,q){return g(f,q,"0")}function l(f,q){function w(X){return 0>X?-1:0<X?1:0}var z;0===(z=w(f.getFullYear()-q.getFullYear()))&&0===(z=w(f.getMonth()-q.getMonth()))&&(z=w(f.getDate()-q.getDate()));return z}function k(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function p(f){f=Pb(new Date(f.W+1900,0,1),f.na);var q=new Date(f.getFullYear()+1,0,4),w=k(new Date(f.getFullYear(),0,4));q=k(q);return 0>=l(w,f)?0>=l(q,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var m=F[d+40>>2];d={Na:F[d>>2],Ma:F[d+4>>2],la:F[d+8>>2],ga:F[d+12>>2],ea:F[d+16>>2],W:F[d+20>>2],ma:F[d+24>>2],na:F[d+28>>2],Ta:F[d+32>>2],La:F[d+36>>
2],Oa:m?C(m):""};c=C(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in m)c=c.replace(new RegExp(n,"g"),m[n]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");m={"%a":function(f){return v[f.ma].substring(0,3)},"%A":function(f){return v[f.ma]},"%b":function(f){return u[f.ea].substring(0,3)},"%B":function(f){return u[f.ea]},"%C":function(f){return h((f.W+1900)/100|0,2)},"%d":function(f){return h(f.ga,2)},"%e":function(f){return g(f.ga,2," ")},"%g":function(f){return p(f).toString().substring(2)},"%G":function(f){return p(f)},"%H":function(f){return h(f.la,
2)},"%I":function(f){f=f.la;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){return h(f.ga+Mb(Lb(f.W+1900)?Nb:Ob,f.ea-1),3)},"%m":function(f){return h(f.ea+1,2)},"%M":function(f){return h(f.Ma,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.la&&12>f.la?"AM":"PM"},"%S":function(f){return h(f.Na,2)},"%t":function(){return"\t"},"%u":function(f){return f.ma||7},"%U":function(f){var q=new Date(f.W+1900,0,1),w=0===q.getDay()?q:Pb(q,7-q.getDay());f=new Date(f.W+1900,f.ea,f.ga);return 0>
l(w,f)?h(Math.ceil((31-w.getDate()+(Mb(Lb(f.getFullYear())?Nb:Ob,f.getMonth()-1)-31)+f.getDate())/7),2):0===l(w,q)?"01":"00"},"%V":function(f){var q=new Date(f.W+1901,0,4),w=k(new Date(f.W+1900,0,4));q=k(q);var z=Pb(new Date(f.W+1900,0,1),f.na);return 0>l(z,w)?"53":0>=l(q,z)?"01":h(Math.ceil((w.getFullYear()<f.W+1900?f.na+32-w.getDate():f.na+1-w.getDate())/7),2)},"%w":function(f){return f.ma},"%W":function(f){var q=new Date(f.W,0,1),w=1===q.getDay()?q:Pb(q,0===q.getDay()?1:7-q.getDay()+1);f=new Date(f.W+
1900,f.ea,f.ga);return 0>l(w,f)?h(Math.ceil((31-w.getDate()+(Mb(Lb(f.getFullYear())?Nb:Ob,f.getMonth()-1)-31)+f.getDate())/7),2):0===l(w,q)?"01":"00"},"%y":function(f){return(f.W+1900).toString().substring(2)},"%Y":function(f){return f.W+1900},"%z":function(f){f=f.La;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Oa},"%%":function(){return"%"}};for(n in m)0<=c.indexOf(n)&&(c=c.replace(new RegExp(n,"g"),m[n](d)));n=Rb(c);if(n.length>
b)return 0;H.set(n,a);return n.length-1}for(var Sb=Array(256),Tb=0;256>Tb;++Tb)Sb[Tb]=String.fromCharCode(Tb);Ma=Sb;O=e.BindingError=Qa("BindingError");Ra=e.InternalError=Qa("InternalError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.R.U.T,c=this.R.S,d=a.R.U.T;for(a=a.R.S;b.Z;)c=b.ha(c),b=b.Z;for(;d.Z;)a=d.ha(a),d=d.Z;return b===d&&c===a};
S.prototype.clone=function(){this.R.S||Ua(this);if(this.R.fa)return this.R.count.value+=1,this;var a=Ya(Object.create(Object.getPrototypeOf(this),{R:{value:Ta(this.R)}}));a.R.count.value+=1;a.R.ca=!1;return a};S.prototype["delete"]=function(){this.R.S||Ua(this);this.R.ca&&!this.R.fa&&P("Object already scheduled for deletion");Wa(this);Xa(this.R);this.R.fa||(this.R.X=void 0,this.R.S=void 0)};S.prototype.isDeleted=function(){return!this.R.S};
S.prototype.deleteLater=function(){this.R.S||Ua(this);this.R.ca&&!this.R.fa&&P("Object already scheduled for deletion");$a.push(this);1===$a.length&&Za&&Za(ab);this.R.ca=!0;return this};U.prototype.ya=function(a){this.sa&&(a=this.sa(a));return a};U.prototype.ra=function(a){this.ba&&this.ba(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=kb;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.ka?ob(this.T.da,{U:this.Ba,S:c,Y:this,X:a}):ob(this.T.da,{U:this,S:a})}var c=this.ya(a);if(!c)return this.ra(a),null;var d=nb(this.T,c);if(void 0!==d){if(0===d.R.count.value)return d.R.S=c,d.R.X=a,d.clone();d=d.clone();this.ra(a);return d}d=this.T.xa(c);d=bb[d];if(!d)return b.call(this);d=this.ja?d.ua:d.pointerType;var g=lb(c,this.T,d.T);return null===g?b.call(this):this.ka?ob(d.T.da,{U:d,S:g,Y:this,X:a}):ob(d.T.da,{U:d,S:g})};
e.getInheritedInstanceCount=function(){return Object.keys(mb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in mb)mb.hasOwnProperty(b)&&a.push(mb[b]);return a};e.flushPendingDeletes=ab;e.setDelayFunction=function(a){Za=a;$a.length&&Za&&Za(ab)};rb=e.UnboundTypeError=Qa("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
function Rb(a){var b=Array(ja(a)+1);ia(a,b,0,b.length);return b}ya.push({wa:function(){Ub()}});
var Xb={f:function(a,b,c,d){A("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},E:function(a){return Vb(a+16)+16},D:function(a,b,c){(new Ja(a)).Aa(b,c);"uncaught_exception"in Ka?Ka.ta++:Ka.ta=1;throw a;},B:function(a,b,c,d,g){var h=La(c);b=L(b);R(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:g},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=H;else if(2===c)k=E;else if(4===c)k=F;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(k[l>>h])},$:null})},k:function(a,b,c,d,g,h,l,k,p,m,n,v,u){n=L(n);h=V(g,h);k&&(k=V(l,k));m&&(m=V(p,m));u=V(v,u);var f=Oa(n);db(f,function(){ub("Cannot construct "+n+" due to unbound types",[d])});Q([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.T;var z=w.da}else z=S.prototype;q=Pa(f,function(){if(Object.getPrototypeOf(this)!==X)throw new O("Use 'new' to construct "+n);if(void 0===Y.aa)throw new O(n+" has no accessible constructor");var yb=Y.aa[arguments.length];if(void 0===
yb)throw new O("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(Y.aa).toString()+") parameters instead!");return yb.apply(this,arguments)});var X=Object.create(z,{constructor:{value:q}});q.prototype=X;var Y=new eb(n,q,X,u,w,h,k,m);w=new U(n,Y,!0,!1);z=new U(n+"*",Y,!1,!1);var zb=new U(n+" const*",Y,!1,!0);bb[a]={pointerType:z,ua:zb};pb(f,q);return[w,z,zb]})},j:function(a,b,c,d,g,h){0<b||A("Assertion failed: undefined");var l=vb(b,c);
g=V(d,g);var k=[h],p=[];Q([],[a],function(m){m=m[0];var n="constructor "+m.name;void 0===m.T.aa&&(m.T.aa=[]);if(void 0!==m.T.aa[b-1])throw new O("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.T.aa[b-1]=function(){ub("Cannot construct "+m.name+" due to unbound types",l)};Q([],l,function(v){m.T.aa[b-1]=function(){arguments.length!==b-1&&
P(n+" called with "+arguments.length+" arguments, expected "+(b-1));p.length=0;k.length=b;for(var u=1;u<b;++u)k[u]=v[u].toWireType(p,arguments[u-1]);u=g.apply(null,k);wb(p);return v[0].fromWireType(u)};return[]});return[]})},c:function(a,b,c,d,g,h,l,k){var p=vb(c,d);b=L(b);h=V(g,h);Q([],[a],function(m){function n(){ub("Cannot call "+v+" due to unbound types",p)}m=m[0];var v=m.name+"."+b;k&&m.T.Ca.push(b);var u=m.T.da,f=u[b];void 0===f||void 0===f.V&&f.className!==m.name&&f.ia===c-2?(n.ia=c-2,n.className=
m.name,u[b]=n):(cb(u,b,v),u[b].V[c-2]=n);Q([],p,function(q){q=Ab(v,q,m,h,l);void 0===u[b].V?(q.ia=c-2,u[b]=q):u[b].V[c-2]=q;return[]});return[]})},A:function(a,b){b=L(b);R(a,{name:b,fromWireType:function(c){var d=Z[c].value;Cb(c);return d},toWireType:function(c,d){return ib(d)},argPackAdvance:8,readValueFromPointer:kb,$:null})},n:function(a,b,c){c=La(c);b=L(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+
T(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:Db(b,c),$:null})},g:function(a,b,c,d,g,h){var l=vb(b,c);a=L(a);g=V(d,g);db(a,function(){ub("Cannot call "+a+" due to unbound types",l)},b-1);Q([],l,function(k){pb(a,Ab(a,[k[0],null].concat(k.slice(1)),null,g,h),b-1);return[]})},d:function(a,b,c,d,g){function h(m){return m}b=L(b);-1===g&&(g=4294967295);var l=La(c);if(0===d){var k=32-8*c;h=function(m){return m<<k>>>k}}var p=-1!=b.indexOf("unsigned");R(a,{name:b,fromWireType:h,toWireType:function(m,
n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+T(n)+'" to '+this.name);if(n<d||n>g)throw new TypeError('Passing a number "'+T(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+g+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Eb(b,l,0!==d),$:null})},b:function(a,b,c){function d(h){h>>=2;var l=I;return new g(G,l[h+1],l[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,
Float32Array,Float64Array][b];c=L(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{za:!0})},o:function(a,b){b=L(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var g=I[d>>2];if(c)for(var h=d+4,l=0;l<=g;++l){var k=d+4+l;if(l==g||0==D[k]){h=C(h,k-h);if(void 0===p)var p=h;else p+=String.fromCharCode(0),p+=h;h=k+1}}else{p=Array(g);for(l=0;l<g;++l)p[l]=String.fromCharCode(D[d+4+l]);p=p.join("")}W(d);return p},toWireType:function(d,g){g instanceof ArrayBuffer&&(g=
new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||P("Cannot pass non-string to std::string");var l=(c&&h?function(){return ja(g)}:function(){return g.length})(),k=Vb(4+l+1);I[k>>2]=l;if(c&&h)ia(g,D,k+4,l+1);else if(h)for(h=0;h<l;++h){var p=g.charCodeAt(h);255<p&&(W(k),P("String has UTF-16 code units that do not fit in 8 bits"));D[k+4+h]=p}else for(h=0;h<l;++h)D[k+4+h]=g[h];null!==d&&d.push(W,k);return k},argPackAdvance:8,
readValueFromPointer:kb,$:function(d){W(d)}})},h:function(a,b,c){c=L(c);if(2===b){var d=la;var g=na;var h=oa;var l=function(){return ma};var k=1}else 4===b&&(d=pa,g=qa,h=ra,l=function(){return I},k=2);R(a,{name:c,fromWireType:function(p){for(var m=I[p>>2],n=l(),v,u=p+4,f=0;f<=m;++f){var q=p+4+f*b;if(f==m||0==n[q>>k])u=d(u,q-u),void 0===v?v=u:(v+=String.fromCharCode(0),v+=u),u=q+b}W(p);return v},toWireType:function(p,m){"string"!==typeof m&&P("Cannot pass non-string to C++ string type "+c);var n=h(m),
v=Vb(4+n+b);I[v>>2]=n>>k;g(m,v+4,n+b);null!==p&&p.push(W,v);return v},argPackAdvance:8,readValueFromPointer:kb,$:function(p){W(p)}})},C:function(a,b){b=L(b);R(a,{Ra:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},p:Cb,q:function(a){4<a&&(Z[a].qa+=1)},i:function(a,b){var c=N[a];void 0===c&&P("_emval_take_value has unknown type "+sb(a));a=c.readValueFromPointer(b);return ib(a)},m:function(){A()},z:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Fb();else return F[Wb()>>
2]=28,-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},t:function(a,b,c){D.copyWithin(a,b,b+c)},e:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);ua(B.buffer);var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},v:function(a,b){var c=0;Hb().forEach(function(d,g){var h=b+c;g=F[a+4*g>>2]=h;for(h=0;h<
d.length;++h)H[g++>>0]=d.charCodeAt(h);H[g>>0]=0;c+=d.length+1});return 0},w:function(a,b){var c=Hb();F[a>>2]=c.length;var d=0;c.forEach(function(g){d+=g.length+1});F[b>>2]=d;return 0},y:function(){return 0},x:function(a,b,c,d){a=Kb.Qa(a);b=Kb.Pa(a,b,c);F[d>>2]=b;return 0},r:function(){},l:function(a,b,c,d){for(var g=0,h=0;h<c;h++){for(var l=F[b+8*h>>2],k=F[b+(8*h+4)>>2],p=0;p<k;p++){var m=D[l+p],n=Jb[a];0===m||10===m?((1===a?ca:y)(ha(n,0)),n.length=0):n.push(m)}g+=k}F[d>>2]=g;return 0},a:B,s:function(){},
u:function(a,b,c,d){return Qb(a,b,c,d)}};
(function(){function a(g){e.asm=g.exports;wa=e.asm.F;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ca&&(clearInterval(Ca),Ca=null),Da&&(g=Da,Da=null,g()))}function b(g){a(g.instance)}function c(g){return Ha().then(function(h){return WebAssembly.instantiate(h,d)}).then(g,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Xb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(g){return y("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){return da||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ub=e.___wasm_call_ctors=function(){return(Ub=e.___wasm_call_ctors=e.asm.G).apply(null,arguments)},tb=e.___getTypeName=function(){return(tb=e.___getTypeName=e.asm.H).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.I).apply(null,arguments)};
var Wb=e.___errno_location=function(){return(Wb=e.___errno_location=e.asm.J).apply(null,arguments)},Vb=e._malloc=function(){return(Vb=e._malloc=e.asm.K).apply(null,arguments)},W=e._free=function(){return(W=e._free=e.asm.L).apply(null,arguments)};e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.M).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.N).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.O).apply(null,arguments)};
e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.P).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.Q).apply(null,arguments)};var Yb;Da=function Zb(){Yb||$b();Yb||(Da=Zb)};
function $b(){function a(){if(!Yb&&(Yb=!0,e.calledRun=!0,!ea)){Ia(ya);Ia(za);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Aa.unshift(b)}Ia(Aa)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();Ia(xa);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=$b;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;$b();e.vec=function(a){var b=new e.VecInt;b.resize(a.length,0);for(var c=0;c<a.length;c++)b.set(c,a[c]);return b};e.vec2=function(a){for(var b=new e.Vec2Int,c=0;c<a.length;c++)b.push_back(e.vec(a[c]));return b};e.arr=function(a){for(var b=[],c=a.size(),d=0;d<c;d++)b.push(a.get(d));return b};e.setup=function(a,b,c){e._setup(e.vec2(a),b,c)};e.solve=function(a){return e.arr(e._solve(e.vec(a)))};
